services:
  frontend:
    container_name: frontend-thequiz
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
    env_file:
      - .env
  backend:
    container_name: backend-thequiz
    build: ./backend
    ports:
      - 3001:3001
    volumes:
      - ./backend:/backend
    env_file:
      - .env
  db:
    image: mysql:8.0.32
    container_name: db
    ports:
      - 3306:3306
    env_file:
      - .env
    restart: 'always'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE


