services:
  frontend:
    container_name: frontend-thequiz
    build: ./frontend
    ports:
      - 3000:5173
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    env_file:
      - .env
  backend:
    container_name: backend-thequiz
    build: ./backend
    ports:
      - 3001:3001
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    env_file:
      - .env
  postgres:
    image: postgres:13.16
    container_name: postgres-quiz-db 
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432


